### ISSUE TITLE
make data available within viz-notebooks

### ISSUE THREAD

**Issue by eglassman** [peparedes/inquire#1]

**Comment by lambdaloop** [comment]
data pushed:
https://github.com/peparedes/inquire/tree/master/viz-notebooks/data

**Comment by eglassman** [comment]
Now I need to figure out how to read the data into the notebook. Maybe pandas is a good start.

**Comment by lambdaloop** [comment]
I'm guessing something like this should work (?):
```
import pandas as pd
pd.read_csv("data/user_studies/results_0.txt", sep=" -- ")
```

**Comment by eglassman** [comment]
Yes, something like that! :)
